import { ModelOption } from "../types";

// Preferred default models per provider (used when user switches provider)
export const DEFAULT_MODELS: Record<string, string> = {
  "anthropic": "anthropic/claude-opus-4-6",
  "openai": "openai/gpt-5.3-codex",
  "google": "google/gemini-3-pro-preview",
  "google-vertex": "google-vertex/gemini-3-pro-preview",
  "openrouter": "openrouter/anthropic/claude-opus-4.6",
  "xai": "xai/grok-4",
};

export const MODELS_BY_PROVIDER: Record<string, ModelOption[]> = {
  "anthropic": [
    { value: "anthropic/claude-haiku-4-5", label: "Claude Haiku 4 5", description: "Input: text+image • Ctx: 195k" },
    { value: "anthropic/claude-haiku-4-5-20251001", label: "Claude Haiku 4 5 20251001", description: "Input: text+image • Ctx: 195k" },
    { value: "anthropic/claude-opus-4-0", label: "Claude Opus 4 0", description: "Input: text+image • Ctx: 195k" },
    { value: "anthropic/claude-opus-4-1", label: "Claude Opus 4 1", description: "Input: text+image • Ctx: 195k" },
    { value: "anthropic/claude-opus-4-1-20250805", label: "Claude Opus 4 1 20250805", description: "Input: text+image • Ctx: 195k" },
    { value: "anthropic/claude-opus-4-20250514", label: "Claude Opus 4 20250514", description: "Input: text+image • Ctx: 195k" },
    { value: "anthropic/claude-opus-4-5", label: "Claude Opus 4 5", description: "Input: text+image • Ctx: 195k" },
    { value: "anthropic/claude-opus-4-5-20251101", label: "Claude Opus 4 5 20251101", description: "Input: text+image • Ctx: 195k" },
    { value: "anthropic/claude-opus-4-6", label: "Claude Opus 4 6", description: "Input: text+image • Ctx: 195k" },
    { value: "anthropic/claude-sonnet-4-0", label: "Claude Sonnet 4 0", description: "Input: text+image • Ctx: 195k" },
    { value: "anthropic/claude-sonnet-4-20250514", label: "Claude Sonnet 4 20250514", description: "Input: text+image • Ctx: 195k" },
    { value: "anthropic/claude-sonnet-4-5", label: "Claude Sonnet 4 5", description: "Input: text+image • Ctx: 195k" },
    { value: "anthropic/claude-sonnet-4-5-20250929", label: "Claude Sonnet 4 5 20250929", description: "Input: text+image • Ctx: 195k" },
  ],
  "openai": [
    { value: "openai/gpt-5", label: "GPT-5", description: "Input: text+image • Ctx: 391k" },
    { value: "openai/gpt-5-chat-latest", label: "GPT-5 Chat Latest", description: "Input: text+image • Ctx: 125k" },
    { value: "openai/gpt-5-codex", label: "GPT-5 Codex", description: "Input: text+image • Ctx: 391k" },
    { value: "openai/gpt-5-mini", label: "GPT-5 Mini", description: "Input: text+image • Ctx: 391k" },
    { value: "openai/gpt-5-nano", label: "GPT-5 Nano", description: "Input: text+image • Ctx: 391k" },
    { value: "openai/gpt-5-pro", label: "GPT-5 Pro", description: "Input: text+image • Ctx: 391k" },
    { value: "openai/gpt-5.1", label: "GPT-5.1", description: "Input: text+image • Ctx: 391k" },
    { value: "openai/gpt-5.1-chat-latest", label: "GPT-5.1 Chat Latest", description: "Input: text+image • Ctx: 125k" },
    { value: "openai/gpt-5.1-codex", label: "GPT-5.1 Codex", description: "Input: text+image • Ctx: 391k" },
    { value: "openai/gpt-5.1-codex-max", label: "GPT-5.1 Codex Max", description: "Input: text+image • Ctx: 391k" },
    { value: "openai/gpt-5.1-codex-mini", label: "GPT-5.1 Codex Mini", description: "Input: text+image • Ctx: 391k" },
    { value: "openai/gpt-5.2", label: "GPT-5.2", description: "Input: text+image • Ctx: 391k" },
    { value: "openai/gpt-5.2-chat-latest", label: "GPT-5.2 Chat Latest", description: "Input: text+image • Ctx: 125k" },
    { value: "openai/gpt-5.2-codex", label: "GPT-5.2 Codex", description: "Input: text+image • Ctx: 391k" },
    { value: "openai/gpt-5.2-pro", label: "GPT-5.2 Pro", description: "Input: text+image • Ctx: 391k" },
    { value: "openai/gpt-5.3-codex", label: "GPT-5.3 Codex", description: "Input: text+image • Ctx: 391k" },
    { value: "openai/gpt-5.3-codex-spark", label: "GPT-5.3 Codex Spark", description: "Input: text+image • Ctx: 125k" },
  ],
  "google": [
    { value: "google/gemini-3-flash-preview", label: "Gemini 3 Flash Preview", description: "Input: text+image • Ctx: 1024k" },
    { value: "google/gemini-3-pro-preview", label: "Gemini 3 Pro Preview", description: "Input: text+image • Ctx: 977k" },
  ],
  "google-vertex": [
    { value: "google-vertex/gemini-3-flash-preview", label: "Gemini 3 Flash Preview", description: "Input: text+image • Ctx: 1024k" },
    { value: "google-vertex/gemini-3-pro-preview", label: "Gemini 3 Pro Preview", description: "Input: text+image • Ctx: 977k" },
  ],
  "openrouter": [
    { value: "openrouter/ai21/jamba-large-1.7", label: "Ai21/Jamba Large 1.7", description: "Input: text • Ctx: 250k" },
    { value: "openrouter/alibaba/tongyi-deepresearch-...", label: "Alibaba/Tongyi Deepresearch ...", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/allenai/olmo-3.1-32b-instruct", label: "Allenai/Olmo 3.1 32B Instruct", description: "Input: text • Ctx: 64k" },
    { value: "openrouter/amazon/nova-2-lite-v1", label: "Amazon/Nova 2 Lite V1", description: "Input: text+image • Ctx: 977k" },
    { value: "openrouter/amazon/nova-lite-v1", label: "Amazon/Nova Lite V1", description: "Input: text+image • Ctx: 293k" },
    { value: "openrouter/amazon/nova-micro-v1", label: "Amazon/Nova Micro V1", description: "Input: text • Ctx: 125k" },
    { value: "openrouter/amazon/nova-premier-v1", label: "Amazon/Nova Premier V1", description: "Input: text+image • Ctx: 977k" },
    { value: "openrouter/amazon/nova-pro-v1", label: "Amazon/Nova Pro V1", description: "Input: text+image • Ctx: 293k" },
    { value: "openrouter/anthropic/claude-3-haiku", label: "Anthropic/Claude 3 Haiku", description: "Input: text+image • Ctx: 195k" },
    { value: "openrouter/anthropic/claude-3.5-haiku", label: "Anthropic/Claude 3.5 Haiku", description: "Input: text+image • Ctx: 195k" },
    { value: "openrouter/anthropic/claude-3.5-sonnet", label: "Anthropic/Claude 3.5 Sonnet", description: "Input: text+image • Ctx: 195k" },
    { value: "openrouter/anthropic/claude-3.7-sonnet", label: "Anthropic/Claude 3.7 Sonnet", description: "Input: text+image • Ctx: 195k" },
    { value: "openrouter/anthropic/claude-3.7-sonnet:...", label: "Anthropic/Claude 3.7 Sonnet:...", description: "Input: text+image • Ctx: 195k" },
    { value: "openrouter/anthropic/claude-haiku-4.5", label: "Anthropic/Claude Haiku 4.5", description: "Input: text+image • Ctx: 195k" },
    { value: "openrouter/anthropic/claude-opus-4", label: "Anthropic/Claude Opus 4", description: "Input: text+image • Ctx: 195k" },
    { value: "openrouter/anthropic/claude-opus-4.1", label: "Anthropic/Claude Opus 4.1", description: "Input: text+image • Ctx: 195k" },
    { value: "openrouter/anthropic/claude-opus-4.5", label: "Anthropic/Claude Opus 4.5", description: "Input: text+image • Ctx: 195k" },
    { value: "openrouter/anthropic/claude-opus-4.6", label: "Anthropic/Claude Opus 4.6", description: "Input: text+image • Ctx: 977k" },
    { value: "openrouter/anthropic/claude-sonnet-4", label: "Anthropic/Claude Sonnet 4", description: "Input: text+image • Ctx: 977k" },
    { value: "openrouter/anthropic/claude-sonnet-4.5", label: "Anthropic/Claude Sonnet 4.5", description: "Input: text+image • Ctx: 977k" },
    { value: "openrouter/arcee-ai/trinity-large-previ...", label: "Arcee Ai/Trinity Large Previ...", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/arcee-ai/trinity-mini", label: "Arcee Ai/Trinity Mini", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/arcee-ai/trinity-mini:free", label: "Arcee Ai/Trinity Mini:Free", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/arcee-ai/virtuoso-large", label: "Arcee Ai/Virtuoso Large", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/auto", label: "Auto", description: "Input: text+image • Ctx: 1953k" },
    { value: "openrouter/baidu/ernie-4.5-21b-a3b", label: "Baidu/Ernie 4.5 21B A3B", description: "Input: text • Ctx: 117k" },
    { value: "openrouter/baidu/ernie-4.5-vl-28b-a3b", label: "Baidu/Ernie 4.5 Vl 28B A3B", description: "Input: text+image • Ctx: 29k" },
    { value: "openrouter/bytedance-seed/seed-1.6", label: "Bytedance Seed/Seed 1.6", description: "Input: text+image • Ctx: 256k" },
    { value: "openrouter/bytedance-seed/seed-1.6-flash", label: "Bytedance Seed/Seed 1.6 Flash", description: "Input: text+image • Ctx: 256k" },
    { value: "openrouter/cohere/command-r-08-2024", label: "Cohere/Command R 08 2024", description: "Input: text • Ctx: 125k" },
    { value: "openrouter/cohere/command-r-plus-08-2024", label: "Cohere/Command R Plus 08 2024", description: "Input: text • Ctx: 125k" },
    { value: "openrouter/deepseek/deepseek-r1", label: "Deepseek/DeepSeek R1", description: "Input: text • Ctx: 63k" },
    { value: "openrouter/deepseek/deepseek-r1-0528", label: "Deepseek/DeepSeek R1 0528", description: "Input: text • Ctx: 160k" },
    { value: "openrouter/deepseek/deepseek-chat", label: "Deepseek/Deepseek Chat", description: "Input: text • Ctx: 160k" },
    { value: "openrouter/deepseek/deepseek-chat-v3-0324", label: "Deepseek/Deepseek Chat V3 0324", description: "Input: text • Ctx: 160k" },
    { value: "openrouter/deepseek/deepseek-chat-v3.1", label: "Deepseek/Deepseek Chat V3.1", description: "Input: text • Ctx: 32k" },
    { value: "openrouter/deepseek/deepseek-v3.1-termi...", label: "Deepseek/Deepseek V3.1 Termi...", description: "Input: text • Ctx: 160k" },
    { value: "openrouter/deepseek/deepseek-v3.1-terminus", label: "Deepseek/Deepseek V3.1 Terminus", description: "Input: text • Ctx: 160k" },
    { value: "openrouter/deepseek/deepseek-v3.2", label: "Deepseek/Deepseek V3.2", description: "Input: text • Ctx: 160k" },
    { value: "openrouter/deepseek/deepseek-v3.2-exp", label: "Deepseek/Deepseek V3.2 Exp", description: "Input: text • Ctx: 160k" },
    { value: "openrouter/google/gemini-2.0-flash-001", label: "Google/Gemini 2.0 Flash 001", description: "Input: text+image • Ctx: 1024k" },
    { value: "openrouter/google/gemini-2.0-flash-lite...", label: "Google/Gemini 2.0 Flash Lite...", description: "Input: text+image • Ctx: 1024k" },
    { value: "openrouter/google/gemini-2.5-flash", label: "Google/Gemini 2.5 Flash", description: "Input: text+image • Ctx: 1024k" },
    { value: "openrouter/google/gemini-2.5-flash-lite", label: "Google/Gemini 2.5 Flash Lite", description: "Input: text+image • Ctx: 1024k" },
    { value: "openrouter/google/gemini-2.5-flash-lite...", label: "Google/Gemini 2.5 Flash Lite...", description: "Input: text+image • Ctx: 1024k" },
    { value: "openrouter/google/gemini-2.5-flash-prev...", label: "Google/Gemini 2.5 Flash Prev...", description: "Input: text+image • Ctx: 1024k" },
    { value: "openrouter/google/gemini-2.5-pro", label: "Google/Gemini 2.5 Pro", description: "Input: text+image • Ctx: 1024k" },
    { value: "openrouter/google/gemini-2.5-pro-previe...", label: "Google/Gemini 2.5 Pro Previe...", description: "Input: text+image • Ctx: 1024k" },
    { value: "openrouter/google/gemini-2.5-pro-preview", label: "Google/Gemini 2.5 Pro Preview", description: "Input: text+image • Ctx: 1024k" },
    { value: "openrouter/google/gemini-3-flash-preview", label: "Google/Gemini 3 Flash Preview", description: "Input: text+image • Ctx: 1024k" },
    { value: "openrouter/google/gemini-3-pro-preview", label: "Google/Gemini 3 Pro Preview", description: "Input: text+image • Ctx: 1024k" },
    { value: "openrouter/google/gemma-3-27b-it", label: "Google/Gemma 3 27B It", description: "Input: text+image • Ctx: 125k" },
    { value: "openrouter/google/gemma-3-27b-it:free", label: "Google/Gemma 3 27B It:Free", description: "Input: text+image • Ctx: 128k" },
    { value: "openrouter/inception/mercury", label: "Inception/Mercury", description: "Input: text • Ctx: 125k" },
    { value: "openrouter/inception/mercury-coder", label: "Inception/Mercury Coder", description: "Input: text • Ctx: 125k" },
    { value: "openrouter/kwaipilot/kat-coder-pro", label: "Kwaipilot/Kat Coder Pro", description: "Input: text • Ctx: 250k" },
    { value: "openrouter/meta-llama/llama-3-8b-instruct", label: "Meta Llama/Llama 3 8B Instruct", description: "Input: text • Ctx: 8k" },
    { value: "openrouter/meta-llama/llama-3.1-405b-in...", label: "Meta Llama/Llama 3.1 405B In...", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/meta-llama/llama-3.1-70b-ins...", label: "Meta Llama/Llama 3.1 70B Ins...", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/meta-llama/llama-3.1-8b-inst...", label: "Meta Llama/Llama 3.1 8B Inst...", description: "Input: text • Ctx: 16k" },
    { value: "openrouter/meta-llama/llama-3.3-70b-ins...", label: "Meta Llama/Llama 3.3 70B Ins...", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/meta-llama/llama-3.3-70b-ins...", label: "Meta Llama/Llama 3.3 70B Ins...", description: "Input: text • Ctx: 125k" },
    { value: "openrouter/meta-llama/llama-4-maverick", label: "Meta Llama/Llama 4 Maverick", description: "Input: text+image • Ctx: 1024k" },
    { value: "openrouter/meta-llama/llama-4-scout", label: "Meta Llama/Llama 4 Scout", description: "Input: text+image • Ctx: 320k" },
    { value: "openrouter/minimax/minimax-m1", label: "Minimax/Minimax M1", description: "Input: text • Ctx: 977k" },
    { value: "openrouter/minimax/minimax-m2", label: "Minimax/Minimax M2", description: "Input: text • Ctx: 192k" },
    { value: "openrouter/minimax/minimax-m2.1", label: "Minimax/Minimax M2.1", description: "Input: text • Ctx: 192k" },
    { value: "openrouter/minimax/minimax-m2.5", label: "Minimax/Minimax M2.5", description: "Input: text • Ctx: 200k" },
    { value: "openrouter/mistralai/codestral-2508", label: "Mistralai/Codestral 2508", description: "Input: text • Ctx: 250k" },
    { value: "openrouter/mistralai/devstral-2512", label: "Mistralai/Devstral 2512", description: "Input: text • Ctx: 256k" },
    { value: "openrouter/mistralai/devstral-medium", label: "Mistralai/Devstral Medium", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/mistralai/devstral-small", label: "Mistralai/Devstral Small", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/mistralai/ministral-14b-2512", label: "Mistralai/Ministral 14B 2512", description: "Input: text+image • Ctx: 256k" },
    { value: "openrouter/mistralai/ministral-3b-2512", label: "Mistralai/Ministral 3B 2512", description: "Input: text+image • Ctx: 128k" },
    { value: "openrouter/mistralai/ministral-8b-2512", label: "Mistralai/Ministral 8B 2512", description: "Input: text+image • Ctx: 256k" },
    { value: "openrouter/mistralai/mistral-large", label: "Mistralai/Mistral Large", description: "Input: text • Ctx: 125k" },
    { value: "openrouter/mistralai/mistral-large-2407", label: "Mistralai/Mistral Large 2407", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/mistralai/mistral-large-2411", label: "Mistralai/Mistral Large 2411", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/mistralai/mistral-large-2512", label: "Mistralai/Mistral Large 2512", description: "Input: text+image • Ctx: 256k" },
    { value: "openrouter/mistralai/mistral-medium-3", label: "Mistralai/Mistral Medium 3", description: "Input: text+image • Ctx: 128k" },
    { value: "openrouter/mistralai/mistral-medium-3.1", label: "Mistralai/Mistral Medium 3.1", description: "Input: text+image • Ctx: 128k" },
    { value: "openrouter/mistralai/mistral-nemo", label: "Mistralai/Mistral Nemo", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/mistralai/mistral-saba", label: "Mistralai/Mistral Saba", description: "Input: text • Ctx: 32k" },
    { value: "openrouter/mistralai/mistral-small-24b-...", label: "Mistralai/Mistral Small 24B ...", description: "Input: text • Ctx: 32k" },
    { value: "openrouter/mistralai/mistral-small-3.1-...", label: "Mistralai/Mistral Small 3.1 ...", description: "Input: text+image • Ctx: 128k" },
    { value: "openrouter/mistralai/mistral-small-3.1-...", label: "Mistralai/Mistral Small 3.1 ...", description: "Input: text+image • Ctx: 125k" },
    { value: "openrouter/mistralai/mistral-small-3.2-...", label: "Mistralai/Mistral Small 3.2 ...", description: "Input: text+image • Ctx: 128k" },
    { value: "openrouter/mistralai/mistral-small-crea...", label: "Mistralai/Mistral Small Crea...", description: "Input: text • Ctx: 32k" },
    { value: "openrouter/mistralai/mixtral-8x22b-inst...", label: "Mistralai/Mixtral 8X22B Inst...", description: "Input: text • Ctx: 64k" },
    { value: "openrouter/mistralai/mixtral-8x7b-instruct", label: "Mistralai/Mixtral 8X7B Instruct", description: "Input: text • Ctx: 32k" },
    { value: "openrouter/mistralai/pixtral-large-2411", label: "Mistralai/Pixtral Large 2411", description: "Input: text+image • Ctx: 128k" },
    { value: "openrouter/mistralai/voxtral-small-24b-...", label: "Mistralai/Voxtral Small 24B ...", description: "Input: text • Ctx: 31k" },
    { value: "openrouter/moonshotai/kimi-k2", label: "Moonshotai/Kimi K2", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/moonshotai/kimi-k2-0905", label: "Moonshotai/Kimi K2 0905", description: "Input: text • Ctx: 256k" },
    { value: "openrouter/moonshotai/kimi-k2-0905:exacto", label: "Moonshotai/Kimi K2 0905:Exacto", description: "Input: text • Ctx: 256k" },
    { value: "openrouter/moonshotai/kimi-k2-thinking", label: "Moonshotai/Kimi K2 Thinking", description: "Input: text • Ctx: 256k" },
    { value: "openrouter/moonshotai/kimi-k2.5", label: "Moonshotai/Kimi K2.5", description: "Input: text+image • Ctx: 256k" },
    { value: "openrouter/nex-agi/deepseek-v3.1-nex-n1", label: "Nex Agi/Deepseek V3.1 Nex N1", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/nousresearch/deephermes-3-mi...", label: "Nousresearch/Deephermes 3 Mi...", description: "Input: text • Ctx: 32k" },
    { value: "openrouter/nousresearch/hermes-4-70b", label: "Nousresearch/Hermes 4 70B", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/nvidia/llama-3.1-nemotron-70...", label: "Nvidia/Llama 3.1 Nemotron 70...", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/nvidia/llama-3.3-nemotron-su...", label: "Nvidia/Llama 3.3 Nemotron Su...", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/nvidia/nemotron-3-nano-30b-a...", label: "Nvidia/Nemotron 3 Nano 30B A...", description: "Input: text • Ctx: 250k" },
    { value: "openrouter/nvidia/nemotron-3-nano-30b-a3b", label: "Nvidia/Nemotron 3 Nano 30B A3B", description: "Input: text • Ctx: 256k" },
    { value: "openrouter/nvidia/nemotron-nano-12b-v2-...", label: "Nvidia/Nemotron Nano 12B V2 ...", description: "Input: text+image • Ctx: 125k" },
    { value: "openrouter/nvidia/nemotron-nano-9b-v2", label: "Nvidia/Nemotron Nano 9B V2", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/nvidia/nemotron-nano-9b-v2:free", label: "Nvidia/Nemotron Nano 9B V2:Free", description: "Input: text • Ctx: 125k" },
    { value: "openrouter/openai/gpt-3.5-turbo", label: "Openai/Gpt 3.5 Turbo", description: "Input: text • Ctx: 16k" },
    { value: "openrouter/openai/gpt-3.5-turbo-0613", label: "Openai/Gpt 3.5 Turbo 0613", description: "Input: text • Ctx: 4k" },
    { value: "openrouter/openai/gpt-3.5-turbo-16k", label: "Openai/Gpt 3.5 Turbo 16K", description: "Input: text • Ctx: 16k" },
    { value: "openrouter/openai/gpt-oss-120b", label: "Openai/Gpt Oss 120B", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/openai/gpt-oss-120b:exacto", label: "Openai/Gpt Oss 120B:Exacto", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/openai/gpt-oss-120b:free", label: "Openai/Gpt Oss 120B:Free", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/openai/gpt-oss-20b", label: "Openai/Gpt Oss 20B", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/openai/gpt-oss-20b:free", label: "Openai/Gpt Oss 20B:Free", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/openai/gpt-oss-safeguard-20b", label: "Openai/Gpt Oss Safeguard 20B", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/openai/o1", label: "Openai/O1", description: "Input: text+image • Ctx: 195k" },
    { value: "openrouter/openai/o3", label: "Openai/O3", description: "Input: text+image • Ctx: 195k" },
    { value: "openrouter/openai/o3-deep-research", label: "Openai/O3 Deep Research", description: "Input: text+image • Ctx: 195k" },
    { value: "openrouter/openai/o3-mini", label: "Openai/O3 Mini", description: "Input: text • Ctx: 195k" },
    { value: "openrouter/openai/o3-mini-high", label: "Openai/O3 Mini High", description: "Input: text • Ctx: 195k" },
    { value: "openrouter/openai/o3-pro", label: "Openai/O3 Pro", description: "Input: text+image • Ctx: 195k" },
    { value: "openrouter/openai/o4-mini", label: "Openai/O4 Mini", description: "Input: text+image • Ctx: 195k" },
    { value: "openrouter/openai/o4-mini-deep-research", label: "Openai/O4 Mini Deep Research", description: "Input: text+image • Ctx: 195k" },
    { value: "openrouter/openai/o4-mini-high", label: "Openai/O4 Mini High", description: "Input: text+image • Ctx: 195k" },
    { value: "openrouter/openrouter/aurora-alpha", label: "Openrouter/Aurora Alpha", description: "Input: text • Ctx: 125k" },
    { value: "openrouter/openrouter/auto", label: "Openrouter/Auto", description: "Input: text+image • Ctx: 1953k" },
    { value: "openrouter/openrouter/free", label: "Openrouter/Free", description: "Input: text+image • Ctx: 195k" },
    { value: "openrouter/prime-intellect/intellect-3", label: "Prime Intellect/Intellect 3", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/qwen/qwen-2.5-72b-instruct", label: "Qwen/Qwen 2.5 72B Instruct", description: "Input: text • Ctx: 32k" },
    { value: "openrouter/qwen/qwen-2.5-7b-instruct", label: "Qwen/Qwen 2.5 7B Instruct", description: "Input: text • Ctx: 32k" },
    { value: "openrouter/qwen/qwen-max", label: "Qwen/Qwen Max", description: "Input: text • Ctx: 32k" },
    { value: "openrouter/qwen/qwen-plus", label: "Qwen/Qwen Plus", description: "Input: text • Ctx: 977k" },
    { value: "openrouter/qwen/qwen-plus-2025-07-28", label: "Qwen/Qwen Plus 2025 07 28", description: "Input: text • Ctx: 977k" },
    { value: "openrouter/qwen/qwen-plus-2025-07-28:th...", label: "Qwen/Qwen Plus 2025 07 28:Th...", description: "Input: text • Ctx: 977k" },
    { value: "openrouter/qwen/qwen-turbo", label: "Qwen/Qwen Turbo", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/qwen/qwen-vl-max", label: "Qwen/Qwen Vl Max", description: "Input: text+image • Ctx: 128k" },
    { value: "openrouter/qwen/qwen3-14b", label: "Qwen/Qwen3 14B", description: "Input: text • Ctx: 40k" },
    { value: "openrouter/qwen/qwen3-235b-a22b", label: "Qwen/Qwen3 235B A22B", description: "Input: text • Ctx: 40k" },
    { value: "openrouter/qwen/qwen3-235b-a22b-2507", label: "Qwen/Qwen3 235B A22B 2507", description: "Input: text • Ctx: 256k" },
    { value: "openrouter/qwen/qwen3-235b-a22b-thinkin...", label: "Qwen/Qwen3 235B A22B Thinkin...", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/qwen/qwen3-30b-a3b", label: "Qwen/Qwen3 30B A3B", description: "Input: text • Ctx: 40k" },
    { value: "openrouter/qwen/qwen3-30b-a3b-instruct-...", label: "Qwen/Qwen3 30B A3B Instruct ...", description: "Input: text • Ctx: 256k" },
    { value: "openrouter/qwen/qwen3-30b-a3b-thinking-...", label: "Qwen/Qwen3 30B A3B Thinking ...", description: "Input: text • Ctx: 32k" },
    { value: "openrouter/qwen/qwen3-32b", label: "Qwen/Qwen3 32B", description: "Input: text • Ctx: 40k" },
    { value: "openrouter/qwen/qwen3-4b", label: "Qwen/Qwen3 4B", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/qwen/qwen3-4b:free", label: "Qwen/Qwen3 4B:Free", description: "Input: text • Ctx: 40k" },
    { value: "openrouter/qwen/qwen3-8b", label: "Qwen/Qwen3 8B", description: "Input: text • Ctx: 31k" },
    { value: "openrouter/qwen/qwen3-coder", label: "Qwen/Qwen3 Coder", description: "Input: text • Ctx: 256k" },
    { value: "openrouter/qwen/qwen3-coder-30b-a3b-ins...", label: "Qwen/Qwen3 Coder 30B A3B Ins...", description: "Input: text • Ctx: 156k" },
    { value: "openrouter/qwen/qwen3-coder-flash", label: "Qwen/Qwen3 Coder Flash", description: "Input: text • Ctx: 977k" },
    { value: "openrouter/qwen/qwen3-coder-next", label: "Qwen/Qwen3 Coder Next", description: "Input: text • Ctx: 256k" },
    { value: "openrouter/qwen/qwen3-coder-plus", label: "Qwen/Qwen3 Coder Plus", description: "Input: text • Ctx: 977k" },
    { value: "openrouter/qwen/qwen3-coder:exacto", label: "Qwen/Qwen3 Coder:Exacto", description: "Input: text • Ctx: 256k" },
    { value: "openrouter/qwen/qwen3-coder:free", label: "Qwen/Qwen3 Coder:Free", description: "Input: text • Ctx: 256k" },
    { value: "openrouter/qwen/qwen3-max", label: "Qwen/Qwen3 Max", description: "Input: text • Ctx: 256k" },
    { value: "openrouter/qwen/qwen3-max-thinking", label: "Qwen/Qwen3 Max Thinking", description: "Input: text • Ctx: 256k" },
    { value: "openrouter/qwen/qwen3-next-80b-a3b-inst...", label: "Qwen/Qwen3 Next 80B A3B Inst...", description: "Input: text • Ctx: 256k" },
    { value: "openrouter/qwen/qwen3-next-80b-a3b-inst...", label: "Qwen/Qwen3 Next 80B A3B Inst...", description: "Input: text • Ctx: 256k" },
    { value: "openrouter/qwen/qwen3-next-80b-a3b-thin...", label: "Qwen/Qwen3 Next 80B A3B Thin...", description: "Input: text • Ctx: 125k" },
    { value: "openrouter/qwen/qwen3-vl-235b-a22b-inst...", label: "Qwen/Qwen3 Vl 235B A22B Inst...", description: "Input: text+image • Ctx: 256k" },
    { value: "openrouter/qwen/qwen3-vl-235b-a22b-thin...", label: "Qwen/Qwen3 Vl 235B A22B Thin...", description: "Input: text+image • Ctx: 128k" },
    { value: "openrouter/qwen/qwen3-vl-30b-a3b-instruct", label: "Qwen/Qwen3 Vl 30B A3B Instruct", description: "Input: text+image • Ctx: 128k" },
    { value: "openrouter/qwen/qwen3-vl-30b-a3b-thinking", label: "Qwen/Qwen3 Vl 30B A3B Thinking", description: "Input: text+image • Ctx: 128k" },
    { value: "openrouter/qwen/qwen3-vl-32b-instruct", label: "Qwen/Qwen3 Vl 32B Instruct", description: "Input: text+image • Ctx: 128k" },
    { value: "openrouter/qwen/qwen3-vl-8b-instruct", label: "Qwen/Qwen3 Vl 8B Instruct", description: "Input: text+image • Ctx: 128k" },
    { value: "openrouter/qwen/qwen3-vl-8b-thinking", label: "Qwen/Qwen3 Vl 8B Thinking", description: "Input: text+image • Ctx: 128k" },
    { value: "openrouter/qwen/qwq-32b", label: "Qwen/Qwq 32B", description: "Input: text • Ctx: 32k" },
    { value: "openrouter/relace/relace-search", label: "Relace/Relace Search", description: "Input: text • Ctx: 250k" },
    { value: "openrouter/sao10k/l3-euryale-70b", label: "Sao10K/L3 Euryale 70B", description: "Input: text • Ctx: 8k" },
    { value: "openrouter/sao10k/l3.1-euryale-70b", label: "Sao10K/L3.1 Euryale 70B", description: "Input: text • Ctx: 32k" },
    { value: "openrouter/stepfun/step-3.5-flash", label: "Stepfun/Step 3.5 Flash", description: "Input: text • Ctx: 250k" },
    { value: "openrouter/stepfun/step-3.5-flash:free", label: "Stepfun/Step 3.5 Flash:Free", description: "Input: text • Ctx: 250k" },
    { value: "openrouter/thedrummer/rocinante-12b", label: "Thedrummer/Rocinante 12B", description: "Input: text • Ctx: 32k" },
    { value: "openrouter/thedrummer/unslopnemo-12b", label: "Thedrummer/Unslopnemo 12B", description: "Input: text • Ctx: 32k" },
    { value: "openrouter/tngtech/deepseek-r1t2-chimera", label: "Tngtech/DeepSeek R1T2 Chimera", description: "Input: text • Ctx: 160k" },
    { value: "openrouter/tngtech/tng-r1t-chimera", label: "Tngtech/Tng R1T Chimera", description: "Input: text • Ctx: 160k" },
    { value: "openrouter/upstage/solar-pro-3:free", label: "Upstage/Solar Pro 3:Free", description: "Input: text • Ctx: 125k" },
    { value: "openrouter/x-ai/grok-3", label: "X Ai/Grok 3", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/x-ai/grok-3-beta", label: "X Ai/Grok 3 Beta", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/x-ai/grok-3-mini", label: "X Ai/Grok 3 Mini", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/x-ai/grok-3-mini-beta", label: "X Ai/Grok 3 Mini Beta", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/x-ai/grok-4", label: "X Ai/Grok 4", description: "Input: text+image • Ctx: 250k" },
    { value: "openrouter/x-ai/grok-4-fast", label: "X Ai/Grok 4 Fast", description: "Input: text+image • Ctx: 1953k" },
    { value: "openrouter/x-ai/grok-4.1-fast", label: "X Ai/Grok 4.1 Fast", description: "Input: text+image • Ctx: 1953k" },
    { value: "openrouter/x-ai/grok-code-fast-1", label: "X Ai/Grok Code Fast 1", description: "Input: text • Ctx: 250k" },
    { value: "openrouter/xiaomi/mimo-v2-flash", label: "Xiaomi/Mimo V2 Flash", description: "Input: text • Ctx: 256k" },
    { value: "openrouter/z-ai/glm-4-32b", label: "Z Ai/Glm 4 32B", description: "Input: text • Ctx: 125k" },
    { value: "openrouter/z-ai/glm-4.5", label: "Z Ai/Glm 4.5", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/z-ai/glm-4.5-air", label: "Z Ai/Glm 4.5 Air", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/z-ai/glm-4.5-air:free", label: "Z Ai/Glm 4.5 Air:Free", description: "Input: text • Ctx: 128k" },
    { value: "openrouter/z-ai/glm-4.5v", label: "Z Ai/Glm 4.5V", description: "Input: text+image • Ctx: 64k" },
    { value: "openrouter/z-ai/glm-4.6", label: "Z Ai/Glm 4.6", description: "Input: text • Ctx: 198k" },
    { value: "openrouter/z-ai/glm-4.6:exacto", label: "Z Ai/Glm 4.6:Exacto", description: "Input: text • Ctx: 200k" },
    { value: "openrouter/z-ai/glm-4.6v", label: "Z Ai/Glm 4.6V", description: "Input: text+image • Ctx: 128k" },
    { value: "openrouter/z-ai/glm-4.7", label: "Z Ai/Glm 4.7", description: "Input: text • Ctx: 198k" },
    { value: "openrouter/z-ai/glm-4.7-flash", label: "Z Ai/Glm 4.7 Flash", description: "Input: text • Ctx: 198k" },
    { value: "openrouter/z-ai/glm-5", label: "Z Ai/Glm 5", description: "Input: text • Ctx: 198k" },
  ],
  "xai": [
    { value: "xai/grok-4", label: "Grok 4", description: "Input: text+image • Ctx: 250k" },
    { value: "xai/grok-4-1-fast", label: "Grok 4 1 Fast", description: "Input: text+image • Ctx: 1953k" },
    { value: "xai/grok-4-1-fast-non-reasoning", label: "Grok 4 1 Fast Non Reasoning", description: "Input: text+image • Ctx: 1953k" },
    { value: "xai/grok-4-fast", label: "Grok 4 Fast", description: "Input: text+image • Ctx: 1953k" },
    { value: "xai/grok-4-fast-non-reasoning", label: "Grok 4 Fast Non Reasoning", description: "Input: text+image • Ctx: 1953k" },
  ],
};

export const PROVIDER_LOGOS: Record<string, string> = {
  "anthropic": "/images/anthropic.svg",
  "openai": "/images/openai.svg",
  "google": "/images/google.svg",
  "openrouter": "/images/openrouter.svg",
  "ollama": "/images/ollama.svg",
  "amazon-bedrock": "/images/aws.svg",
  "azure-openai-responses": "/images/azure.svg",
  "cerebras": "/images/cerebras.svg",
  "github-copilot": "/images/github.svg",
  "google-antigravity": "/images/google.svg",
  "google-gemini-cli": "/images/google.svg",
  "google-vertex": "/images/google.svg",
  "groq": "/images/groq.svg",
  "huggingface": "/images/huggingface.svg",
  "kimi-coding": "/images/moonshot.svg",
  "minimax": "/images/minimax.svg",
  "mistral": "/images/mistral.svg",
  "openai-codex": "/images/openai.svg",
  "opencode": "/images/code.svg",
  "vercel-ai-gateway": "/images/vercel.svg",
  "xai": "/images/grok.svg",
  "zai": "/images/zhipu.svg"
};

export const EMOJI_OPTIONS = ["🦞", "🤖", "🧠", "⚡", "🔮", "🦉", "🦊", "🐯", "🦁", "🦄", "👽", "👾", "🐉", "🦕", "🦍", "🐕", "🐈", "🐙", "🍄", "🌎"];

export const SKILL_ICONS: Record<string, string> = {
  "1password": "/images/1password.svg",
  "apple-notes": "/images/apple-notes.svg",
  "apple-reminders": "/images/checklist.svg",
  "bear-notes": "/images/bear.svg",
  "blogwatcher": "/images/terminal.svg",
  "blucli": "/images/terminal.svg",
  "bluebubbles": "/images/message.svg",
  "camsnap": "/images/camera.svg",
  "clawhub": "/images/terminal.svg",
  "coding-agent": "/images/code.svg",
  "eightctl": "/images/moon.svg",
  "gemini": "/images/google.svg",
  "gifgrep": "/images/terminal.svg",
  "github": "/images/github.svg",
  "gog": "/images/google-drive.svg",
  "goplaces": "/images/google-maps.svg",
  "healthcheck": "/images/terminal.svg",
  "himalaya": "/images/terminal.svg",
  "imsg": "/images/message.svg",
  "local-places": "/images/google-maps.svg",
  "mcporter": "/images/terminal.svg",
  "model-usage": "/images/chart.svg",
  "nano-banana-pro": "/images/google.svg",
  "nano-pdf": "/images/pdf.svg",
  "notion": "/images/notion.svg",
  "obsidian": "/images/obsidian.svg",
  "openai-image-gen": "/images/openai.svg",
  "openai-whisper": "/images/openai.svg",
  "openai-whisper-api": "/images/openai.svg",
  "openhue": "/images/philips-hue.svg",
  "oracle": "/images/terminal.svg",
  "ordercli": "/images/terminal.svg",
  "peekaboo": "/images/camera.svg",
  "sag": "/images/mic.svg",
  "session-logs": "/images/chart.svg",
  "sherpa-onnx-tts": "/images/mic.svg",
  "skill-creator": "/images/code.svg",
  "slack": "/images/slack.svg",
  "songsee": "/images/chart.svg",
  "sonoscli": "/images/sonos.svg",
  "spotify-player": "/images/spotify.svg",
  "summarize": "/images/pdf.svg",
  "things-mac": "/images/checklist.svg",
  "tmux": "/images/terminal.svg",
  "trello": "/images/trello.svg",
  "video-frames": "/images/camera.svg",
  "voice-call": "/images/mic.svg",
  "wacli": "/images/whatsapp.svg",
  "weather": "/images/weather.svg"
};
